## https://taplo.tamasfe.dev/configuration/#configuration-file

include = ["**/*.toml"]
exclude = ["target/**"]

[formatting]
## Align consecutive entries vertically.
align_entries = false
## Align consecutive comments after entries and items vertically.
align_comments = true
## Put trailing commas for multiline arrays.
array_trailing_comma = true
## Automatically expand arrays to multiple lines when they exceed column_width characters.
array_auto_expand = true
## Automatically collapse arrays if they fit in one line.
array_auto_collapse = false # Default: true
## Omit white space padding from single-line arrays
compact_arrays = true
## Omit whitespace padding inside inline tables.
compact_inline_tables = false
## Expand values (e.g. arrays) inside inline tables.
inline_table_expand = true
## Omit whitespace around =.
compact_entries = false
## Target maximum column width after which arrays are expanded into new lines.
## Note that this is not set in stone, and works on a best-effort basis.
column_width = 100 # Default: 80
## Indent subtables if they come in order.
indent_tables = false
## Indent entries under tables.
indent_entries = false
## Indentation to use, should be tabs or spaces but technically could be anything.
indent_string = "    " # Default: 2 spaces
## Add trailing newline to the source.
trailing_newline = true
## Alphabetically reorder keys that are not separated by blank lines.
reorder_keys = false
## Alphabetically reorder array values that are not separated by blank lines.
reorder_arrays = false
## Alphabetically reorder inline tables.
reorder_inline_tables = false
## The maximum amount of consecutive blank lines allowed.
allowed_blank_lines = 1 # Default: 2
## Use CRLF line endings.
crlf = false

[[rule]]
keys = ["dependencies", "dev-dependencies", "build-dependencies"]
formatting = { reorder_keys = true }
