name: Bug Report
description: File a bug report
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: "Steps to reproduce the behavior:"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Explain what you expected to happen..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add any other context about the problem here."
      placeholder: "Additional details..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "Please make sure to include any relevant information such as screenshots, logs, or code snippets that may help in diagnosing the issue."

  - type: checkboxes
    id: willing-to-submit-pr
    attributes:
      label: "Are you willing to submit a PR to fix this bug?"
      description: "Let us know if you are willing to contribute a fix by submitting a Pull Request."
      options:
        - label: "Yes, I would like to submit a PR."
