name: workspace

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  TAPLO_CLI_VERSION: 0.10.0

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Cache taplo-cli
        id: cache-taplo
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/taplo
          key: ${{ runner.os }}-taplo-${{ env.TAPLO_CLI_VERSION }}

      - name: Install taplo-cli if not cached
        if: steps.cache-taplo.outputs.cache-hit != 'true'
        shell: bash
        run: cargo install taplo-cli@${TAPLO_CLI_VERSION} --locked

      - name: Run taplo fmt
        run: taplo fmt --check

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  check-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
