name: workspace

on:
  push:
    branches: master
  pull_request:
    path-ignore:
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v5

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check Code Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Code Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings

#  coverage:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Sources
#        uses: actions/checkout@v5
#
#      - name: Install Rust Toolchain
#        uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: stable
#          override: true
#
#      - name: Generate Code Coverage
#        uses: actions-rs/tarpaulin@v0.1
#        with:
#          args: '--all-features'
#
#      - name: Upload Code Coverage
#        uses: codecov/codecov-action@v3
